In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_excel("Medals.xlsx")

In [3]:
df=data.copy()

In [4]:
df.head()

Rank                    Team/NOC  Gold  Silver  Bronze  Total  \
0     1    United States of America    39      41      33    113   
1     2  People's Republic of China    38      32      18     88   
2     3                       Japan    27      14      17     58   
3     4               Great Britain    22      21      22     65   
4     5                         ROC    20      28      23     71   

   Rank by Total  
0              1  
1              2  
2              5  
3              4  
4              3

In [5]:
df.describe()

Rank       Gold     Silver     Bronze       Total  Rank by Total
count  93.000000  93.000000  93.000000  93.000000   93.000000      93.000000
mean   46.333333   3.655914   3.634409   4.322581   11.612903      43.494624
std    26.219116   7.022471   6.626339   6.210372   19.091332      24.171769
min     1.000000   0.000000   0.000000   0.000000    1.000000       1.000000
25%    24.000000   0.000000   0.000000   1.000000    2.000000      23.000000
50%    46.000000   1.000000   1.000000   2.000000    4.000000      47.000000
75%    70.000000   3.000000   4.000000   5.000000   11.000000      66.000000
max    86.000000  39.000000  41.000000  33.000000  113.000000      77.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Rank           93 non-null     int64 
 1   Team/NOC       93 non-null     object
 2   Gold           93 non-null     int64 
 3   Silver         93 non-null     int64 
 4   Bronze         93 non-null     int64 
 5   Total          93 non-null     int64 
 6   Rank by Total  93 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 5.2+ KB


Data standradization 

In [7]:
data=pd.read_excel("coaches.xlsx")

In [8]:
df1=data.copy()

In [9]:
df1

Name                         NOC         Discipline  \
0           ABDELMAGID Wael                       Egypt           Football   
1                 ABE Junya                       Japan         Volleyball   
2             ABE Katsuhiko                       Japan         Basketball   
3              ADAMA Cherif               Côte d'Ivoire           Football   
4                AGEBA Yuya                       Japan         Volleyball   
..                      ...                         ...                ...   
389  ZAMORA PEDREIRA Javier                       Spain         Basketball   
390      ZAMPIERI Francesca               Liechtenstein  Artistic Swimming   
391          ZHANG Xiaohuan  People's Republic of China  Artistic Swimming   
392              ZIJP Simon                 Netherlands             Hockey   
393           ZONDI Nkuliso                South Africa             Hockey   

     Event  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN  
..     ...  
389    NaN  
390   Duet  
391    NaN  
392    NaN  
393  Women  

[394 rows x 4 columns]

In [10]:
df.shape[0]

93

In [11]:
df.shape[1]

7

In [12]:
df1.shape[0]

394

In [13]:
df1.shape[1]

4

In [14]:
df.columns

Index(['Rank', 'Team/NOC', 'Gold', 'Silver', 'Bronze', 'Total',
       'Rank by Total'],
      dtype='object')

In [15]:
df1.columns

Index(['Name', 'NOC', 'Discipline', 'Event'], dtype='object')

In [16]:
df.max()

Rank                    86
Team/NOC         Venezuela
Gold                    39
Silver                  41
Bronze                  33
Total                  113
Rank by Total           77
dtype: object

In [17]:
df.min()

Rank                     1
Team/NOC         Argentina
Gold                     0
Silver                   0
Bronze                   0
Total                    1
Rank by Total            1
dtype: object

In [33]:
df["Gold"].unique()

array([39, 38, 27, 22, 20, 17, 10,  7,  6,  4,  3,  2,  1,  0],
      dtype=int64)

In [19]:
df["Rank"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 38, 39, 41, 42, 44, 45, 46, 48, 49, 50, 52, 53, 54, 55, 56,
       58, 59, 63, 66, 67, 68, 69, 70, 71, 72, 74, 77, 83, 84, 85, 86],
      dtype=int64)

In [20]:
df[["Gold","Team/NOC"]]

Gold                    Team/NOC
0     39    United States of America
1     38  People's Republic of China
2     27                       Japan
3     22               Great Britain
4     20                         ROC
..   ...                         ...
88     0                       Ghana
89     0                     Grenada
90     0                      Kuwait
91     0         Republic of Moldova
92     0        Syrian Arab Republic

[93 rows x 2 columns]

In [21]:
df[["Gold","Team/NOC"]].describe(
)

Gold
count  93.000000
mean    3.655914
std     7.022471
min     0.000000
25%     0.000000
50%     1.000000
75%     3.000000
max    39.000000

In [22]:
df1.describe("")

Name    NOC  Discipline Event
count             394    394         394   249
unique            381     61           9     6
top     ELAFANDI Nour  Japan  Basketball   Men
freq                2     35          74    94

In [23]:
df1[["Event"]]

Event
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
..     ...
389    NaN
390   Duet
391    NaN
392    NaN
393  Women

[394 rows x 1 columns]

In [24]:
df1["Event"].unique()

array([nan, 'Men', 'Softball', 'Women', 'Duet', 'Team', 'Baseball'],
      dtype=object)

In [25]:
missing_data=df1.isnull()

In [26]:
missing_data


Name    NOC  Discipline  Event
0    False  False       False   True
1    False  False       False   True
2    False  False       False   True
3    False  False       False   True
4    False  False       False   True
..     ...    ...         ...    ...
389  False  False       False   True
390  False  False       False  False
391  False  False       False   True
392  False  False       False   True
393  False  False       False  False

[394 rows x 4 columns]

In [27]:
df1.isnull().any()

Name          False
NOC           False
Discipline    False
Event          True
dtype: bool

In [28]:
missing_data.columns

Index(['Name', 'NOC', 'Discipline', 'Event'], dtype='object')

In [29]:
missing_data.columns.value_counts()

Name          1
Discipline    1
Event         1
NOC           1
dtype: int64

In [30]:
missing_data.columns.values.tolist()

['Name', 'NOC', 'Discipline', 'Event']

In [31]:
for col in missing_data.columns.values.tolist():
    print(missing_data[(col)].value_counts())
    print("\n")
    
    
    

False    394
Name: Name, dtype: int64


False    394
Name: NOC, dtype: int64


False    394
Name: Discipline, dtype: int64


False    249
True     145
Name: Event, dtype: int64




In [32]:
df1["Event"].value_counts().idxmax()

'Men'

In [34]:
df1["Event"].value_counts()


Men         94
Women       88
Duet        27
Softball    20
Team        14
Baseball     6
Name: Event, dtype: int64

In [35]:
df1["Event"].replace(np.nan,"men",inplace=True)

In [36]:
df1

Name                         NOC         Discipline  \
0           ABDELMAGID Wael                       Egypt           Football   
1                 ABE Junya                       Japan         Volleyball   
2             ABE Katsuhiko                       Japan         Basketball   
3              ADAMA Cherif               Côte d'Ivoire           Football   
4                AGEBA Yuya                       Japan         Volleyball   
..                      ...                         ...                ...   
389  ZAMORA PEDREIRA Javier                       Spain         Basketball   
390      ZAMPIERI Francesca               Liechtenstein  Artistic Swimming   
391          ZHANG Xiaohuan  People's Republic of China  Artistic Swimming   
392              ZIJP Simon                 Netherlands             Hockey   
393           ZONDI Nkuliso                South Africa             Hockey   

     Event  
0      men  
1      men  
2      men  
3      men  
4      men  
..     ...  
389    men  
390   Duet  
391    men  
392    men  
393  Women  

[394 rows x 4 columns]

In [37]:
dum=pd.get_dummies(df1["Event"])

In [38]:
dum

Baseball  Duet  Men  Softball  Team  Women  men
0           0     0    0         0     0      0    1
1           0     0    0         0     0      0    1
2           0     0    0         0     0      0    1
3           0     0    0         0     0      0    1
4           0     0    0         0     0      0    1
..        ...   ...  ...       ...   ...    ...  ...
389         0     0    0         0     0      0    1
390         0     1    0         0     0      0    0
391         0     0    0         0     0      0    1
392         0     0    0         0     0      0    1
393         0     0    0         0     0      1    0

[394 rows x 7 columns]

In [39]:
df1=pd.concat([df1,dum],axis=1)

In [40]:
df1.head(
)

Name            NOC  Discipline Event  Baseball  Duet  Men  \
0  ABDELMAGID Wael          Egypt    Football   men         0     0    0   
1        ABE Junya          Japan  Volleyball   men         0     0    0   
2    ABE Katsuhiko          Japan  Basketball   men         0     0    0   
3     ADAMA Cherif  Côte d'Ivoire    Football   men         0     0    0   
4       AGEBA Yuya          Japan  Volleyball   men         0     0    0   

   Softball  Team  Women  men  
0         0     0      0    1  
1         0     0      0    1  
2         0     0      0    1  
3         0     0      0    1  
4         0     0      0    1

In [41]:
df1.drop("Event",axis=1,inplace=True)

In [42]:
df1.head()

Name            NOC  Discipline  Baseball  Duet  Men  Softball  \
0  ABDELMAGID Wael          Egypt    Football         0     0    0         0   
1        ABE Junya          Japan  Volleyball         0     0    0         0   
2    ABE Katsuhiko          Japan  Basketball         0     0    0         0   
3     ADAMA Cherif  Côte d'Ivoire    Football         0     0    0         0   
4       AGEBA Yuya          Japan  Volleyball         0     0    0         0   

   Team  Women  men  
0     0      0    1  
1     0      0    1  
2     0      0    1  
3     0      0    1  
4     0      0    1

In [43]:
df1["Discipline"].unique()

array(['Football', 'Volleyball', 'Basketball', 'Hockey',
       'Baseball/Softball', 'Handball', 'Rugby Sevens',
       'Artistic Swimming', 'Water Polo'], dtype=object)

In [46]:
df1["Discipline"].value_counts()

Basketball           74
Artistic Swimming    69
Football             59
Hockey               45
Volleyball           45
Handball             29
Baseball/Softball    26
Rugby Sevens         25
Water Polo           22
Name: Discipline, dtype: int64

In [48]:
df2=pd.read_excel("Athletes.xlsx")

In [49]:
df.head()

Rank                    Team/NOC  Gold  Silver  Bronze  Total  \
0     1    United States of America    39      41      33    113   
1     2  People's Republic of China    38      32      18     88   
2     3                       Japan    27      14      17     58   
3     4               Great Britain    22      21      22     65   
4     5                         ROC    20      28      23     71   

   Rank by Total  
0              1  
1              2  
2              5  
3              4  
4              3